name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            rm -rf ${{ secrets.TARGET_DIR }}
            mkdir -p ${{ secrets.TARGET_DIR }}
            cd ${{ secrets.TARGET_DIR }}
            git clone https://github.com/MrSohailAhmad/new_express_app.git.
            npm install
            pm2 restart app || pm2 start index.js --name "app"
