name: Node.js CI and Deploy to EC2

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run build --if-present

      - name: Deploy to EC2
        if: matrix.node-version == '20.x' && github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            # Install Node.js 18 and PM2 (only once if needed)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2

            # Deploy your Node.js app
            pm2 stop app || true
            rm -rf ${{ secrets.TARGET_DIR }}
            git clone https://github.com/MrSohailAhmad/new_express_app.git ${{ secrets.TARGET_DIR }}
            cd ${{ secrets.TARGET_DIR }}
            npm install
            pm2 start index.js --name app
